import React from 'react';
import { useCurrentFrame, interpolate, AbsoluteFill } from 'remotion';
import { Mic } from 'lucide-react';
import { DL, DL_SERIF, DL_SANS, DL_MONO, DL_EASE, DCLAMP, SiteBg, Kicker, useDlRise } from '../../lib/danslab';

// =============================================================================
// Origin 7/14 — the YouTube pipeline. VO 0.8s (17.5s): ten steps stagger in as
// Brian lists them; the meta line "even this voice was generated" lands with a
// mic glow (~f420).
// =============================================================================
export const compositionConfig = { id: 'DoPipeline', durationInSeconds: 19.2, fps: 30, width: 1920, height: 1080 };

const STEPS = ['Research', 'Script', 'Design', 'Scenes', 'Voice', 'Subtitles', 'Render', 'QA', 'Final', 'Publish'];
const STEP0 = 96, GAP = 18;
const META = 420;

const DoPipeline: React.FC = () => {
  const frame = useCurrentFrame();
  const rise = useDlRise();
  const metaOp = interpolate(frame, [META, META + 16], [0, 1], { ...DCLAMP, easing: DL_EASE.out });
  const glow = 0.5 + 0.5 * Math.abs(Math.sin(frame / 14));
  const flow = interpolate(frame, [STEP0 + GAP * 10, STEP0 + GAP * 10 + 30], [0, 1], { ...DCLAMP, easing: DL_EASE.inOut });

  return (
    <AbsoluteFill style={{ fontFamily: DL_SANS }}>
      <SiteBg glow={DL.gold} />
      <Kicker n="06" label="THE PIPELINE // 10 STEPS" />

      <div style={{ position: 'absolute', top: 210, left: 120, ...rise(10, 20) }}>
        <span style={{ fontFamily: DL_SERIF, fontWeight: 500, fontSize: 76, color: DL.text }}>
          A finished video comes out <span style={{ fontStyle: 'italic', color: DL.gold }}>the other end.</span>
        </span>
      </div>

      {/* two rows of five steps */}
      <div style={{ position: 'absolute', top: 420, left: 160, right: 160 }}>
        <div style={{ position: 'relative', display: 'flex', flexWrap: 'wrap', gap: 24, justifyContent: 'center' }}>
          <div style={{ position: 'absolute', top: '50%', left: 40, right: 40, height: 4, borderRadius: 999, background: '#ffffff0c', overflow: 'hidden' }}>
            <div style={{ height: '100%', width: '100%', background: `linear-gradient(90deg, ${DL.red}, ${DL.gold})`, transform: `scaleX(${flow})`, transformOrigin: 'left' }} />
          </div>
          {STEPS.map((s, i) => {
            const at = STEP0 + i * GAP;
            const op = interpolate(frame, [at, at + 11], [0, 1], { ...DCLAMP, easing: DL_EASE.out });
            const y = interpolate(frame, [at, at + 11], [22, 0], { ...DCLAMP, easing: DL_EASE.out });
            return (
              <div key={s} style={{ opacity: op, transform: `translateY(${y}px)`, zIndex: 1, background: DL.panel, border: `1px solid ${DL.border}`, borderRadius: 12, padding: '22px 34px', display: 'flex', alignItems: 'center', gap: 14 }}>
                <span style={{ fontFamily: DL_MONO, fontSize: 19, color: DL.faint }}>{String(i + 1).padStart(2, '0')}</span>
                <span style={{ fontSize: 30, fontWeight: 600, color: DL.text }}>{s}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* meta voice moment */}
      <div style={{ position: 'absolute', bottom: 110, left: 0, right: 0, display: 'flex', justifyContent: 'center', opacity: metaOp }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 22, border: `1px solid ${DL.red}66`, background: `${DL.red}10`, borderRadius: 999, padding: '20px 44px', boxShadow: `0 0 ${50 * glow}px ${DL.red}33` }}>
          <Mic size={34} color={DL.red} />
          <span style={{ fontFamily: DL_SERIF, fontStyle: 'italic', fontSize: 40, color: DL.text }}>
            Even this voice… <span style={{ color: DL.red }}>was generated by this system.</span>
          </span>
        </div>
      </div>
    </AbsoluteFill>
  );
};
export default DoPipeline;
